#可以热更新的配置，不需要重启程序
shuqiUpdater:
  updateSleep:
    600

mianFeiTXTUpdater:
  updateSleep:
    3600

quanBenUpdater:
  updateSleep:
    18000

searchHistoryCrawler:
  updateSleep:
    86400


shuqiNewFinder:
  updateSleep:
    186400

